name: tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  cutcode_shop-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@2
      with:
        php-version: '8.1'
        tools: composer:v2
    - uses: actions/checkout@v4

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
    - name: Install Dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader
      
    - name: Generate key
      run: php artisan key:generate
      
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Set up MySQL
      env:
        DB_USERNAME: root
        DB_PASSWORD: root
        DB_DATABASE: cutcode_shop_test
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USERNAME }} -p${{ env.DB_PASSWORD }}

    - name: Create Database Schema
      env:
        DB_DATABASE: cutcode_shop_test
        DB_PORT: ${{ job.services.mysql.ports['3306'] }}
        DB_USERNAME: root
        DB_PASSWORD: ''
      run: php artisan migrate
        
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        DB_PASSWORD: root
      run: php artisan test
